home/urls.py
from django.urls import path, re_path

from. import views

urlpatterns=[
    path("", views.index, name='home'),
    re_path(r'^blog/$', views.blog, name='blog'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^ajax/validate_your_email/$', views.validate_your_email, name='validate_your_email'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models

# Create your models here.
class subscribers(models.Model):
    your_email = models.CharField(max_length=45)

home/forms.py
from django import forms
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User


class subsform(forms.Form):
    your_email = forms.EmailField(label='Email', max_length=100)

home/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import subscribers
from .forms import subsform

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = subsform(request.POST);
        if form.is_valid():
            your_email=form.cleaned_data['your_email']
            if subscribers.objects.filter(your_email__iexact=your_email).exists():
                pass
            else:
                p=subscribers(your_email=your_email)
                p.save()
    else:
        form = subsform()

    return render(request, "home/index.html", {'form': form})

def validate_your_email(request):
    your_email = request.GET.get('your_email', None)
    data = {
        'is_taken': subscribers.objects.filter(your_email__iexact=your_email).exists()
    }
    return JsonResponse(data)

def blog(request):
    return render(request, "home/blog.html")

def about(request):
    return render(request, "home/about.html")

home/templates/home/about.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Time Travel</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<h1>Time Travel</h1>
				<p>A Blog on time travel, sign up to get updates on the blog.<br>Visit The Home Page Right Now</p>
            <form id="signup-form" method="post" action="{% url 'home' %}">
          {% csrf_token %}
          <input type="submit" value="Home" />
        </form>
      </header>
      <h1>About The Author</h1>
      <div class="transbox">
        <p> WRITE ABOUT THE AUTHOR HERE</p>
      </div>
		<!-- Signup Form -->




		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
					<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
				</ul>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

home/templates/home/blog.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Time Travel</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body class="is-preload" background="{%static 'images/11.jpeg'%}">

		<!-- Header -->
    <header id="header">
      <form id="signup-form" method="post" action="{% url 'home' %}">
        {% csrf_token %}
        <input type="submit" value="Home" />
      </form>
    	<h1 align=center>Space And Time</h1>
				<p>A Blog on time travel.<br>24 october 2017</p>

  </header>
  <div class="transbox">
  <p> Every guy has a different opinion i am just stating mine. I see space and time very inter related and complexly beautiful .If you have read sir Einsteins theories you must have encountered the time travel subject intriguing and full of excitement of course you have seen movies revolving a round time travel, but sir Einstein placed the subject of time travel off charts. Most of you probably know the renowned   E=MC^2   term, well as he said to time travel one must have a speed of light which literally diminishes the mass of the respected body to zero. Of course not possible and here the scientist puts a full stop to the fantasies of time traveling.<br>Though, he did give another theory he stated if someone travels in space he might experience that time around him slows down. I am not a scientist, i am just a student, a philosopher fond of time, space and time traveling so can't give you enough proof though i have tried to find evidences but all i have is my brain my imagination and facts that a normal human being understands.

The things i found were beyond my understanding. All Einsteins theories are mind boggling but  i did find an easy going example which i understood and in simple words :
<br>" calculations show that it would take a rocket 10 years to reach the planet Pluto from earth and another 10 years to come back from Pluto to earth while the human experiences a time span of 20 years, a human on earth would experience around 50 years. "
<br>
INDEED AN AMAZING FACT, at-least for me
so how do we put this in terms of time traveling, or is it even time traveling?
In reference to that what i suggest is, it's a side effect of traveling in space maybe some unknown force or effect related to dark matter.
<br><br>
AT-LEAST  we know there's something to prove that we can use object phenomenon's to use time for our greater good.
I will continue my findings in the next blog, till then sayonara my friends.</p>
</div>

		<!-- Signup Form
			<form id="signup-form" method="post" action="#">
				{% csrf_token %}
				{{ form }}
				<input type="submit" value="Sign Up" />
			</form>
			<h2>Read The Blog <br> Visit Our Fb And Instagram</h2>
			<form id="signup-form" method="post" action="{% url 'blog' %}">
				<input type="submit" value="Continue to the Blog Page" />
			</form>
      -->

		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
					<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
				</ul>
			</footer>

		<!-- Scripts -->
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

home/templates/home/index.html
{% load static %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Time Travel</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<h1>Time Travel</h1>
				<p>A Blog on time travel, sign up to get updates on the blog.</p>
			</header>

		<!-- Signup Form -->
			<form id="signup-form" method="post" action="{% url 'home'%}">
				{% csrf_token %}
				{{ form }}
				<input type="submit" value="Sign Up" />
			</form>
			<h2>Read The Blog <br> Visit Our Fb And Instagram</h2>
			<form id="signup-form" method="post" action="{% url 'blog' %}">
				{% csrf_token %}
				<input type="submit" value="Continue to the Blog Page" />
			</form>
				<h2>To Know About The Author, Click Below.</h2>
			<form id="signup-form" method="post" action="{% url 'about' %}">
				{% csrf_token %}
				<input type="submit" value="About the author" />
			</form>


		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
					<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
				</ul>
			</footer>

		<!-- Scripts -->
		<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
		<script>
 		$("#id_your_email").change(function () {
	 		var your_email = $(this).val();

	 	$.ajax({
		 	url: '/ajax/validate_your_email/',
		 	data: {
			 	'your_email': your_email
		 	},
		 	dataType: 'json',
		 		success: function (data) {
			 	if (data.is_taken) {
				 	alert("A user with this email already exists.");
			 	}
		 	}
	 	});

 		});
	</script>

			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>